# https://taskfile.dev

version: '3'

vars:

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    desc: Builds the app
    cmds:
      - go mod tidy
      - go build -o ./bin/ocm-discord-bot -v ./src/
  run:
    desc: Start the app
    cmds:
      - ./bin/ocm-discord-bot
  br:
    desc: Build and run the app
    cmds:
      - task: build
      - task: run
  docker-build:
    desc: Build the docker image
    cmds:
      - docker build --tag docker-ocm-meta-bot .
  docker-run:
    desc: Runs the docker image
    cmds:
      - docker run -d --env DISCORD_API_KEY --name ocm-meta-bot docker-ocm-meta-bot